#!/bin/bash
# Runserv, by Chris Atenasio
ulimit -c unlimited

while :; do
	./mangband -Z
	if [ -f core ] ; then
		mv core cores/`/bin/date +"%Y%m%d%I%M%S"`
	fi
	if [ -f lib/data/mangband.log ] ; then
		gzip lib/data/mangband.log
		mv lib/data/mangband.log.gz lib/data/`/bin/date +"%Y%m%d%I%M.log.gz"`
	fi
done
