-- Tables with descriptive text about the classes, to be displayed 
-- during character creation process. - C. Blue

function get_class_diz(r_title, l)
    local i
    i = 0
    while __classes_diz[(i * 2) + 1] ~= nil do
        if __classes_diz[(i * 2) + 1] == r_title then
            if __classes_diz[(i * 2) + 2][l + 1] == nil then
                return ""
            else
                return __classes_diz[(i * 2) + 2][l + 1]
            end
        end
        i = i + 1
    end
    return ""
end

__classes_diz = {

--  "12345678901234567890123456789012345678901234567890",

"Warrior",
    {"\255uWarriors\255U solve most problems by cutting them to",
    "pieces. They are good at fighting and bows/throws",
    "but bad at most other things, although they can",
    "train to use magic devices. They are able to dual-",
    "wield one-handers, which requires light armour.",
    "They can also choose the paths of an unbeliever,",
    "who disbelieves in magic so strongly, negating it,",
    "or the path of a martial artist, foregoing weapons",
    "for fighting bare-handed instead.",
    "In most cases warrior are seen using two-handers,",
    "or one-hander and shield, and heavy armour to go",
    "with either."},

"Istar",
    {"\255uIstari\255U, as mages are called in elvish, are the",
    "all-around best magicians having both devastating",
    "and very useful support spells. On the downside",
    "they are the worst in close combat, and usually",
    "stick with a mage staff instead of weapons.",
    "Once they learn the Disruption Shield spell and",
    "are able to use it reliably, they become very hard",
    "to kill, but until then it will be a dangerous",
    "journey full of peril for every novice istar.",
    "",
    "",
    "",},

"Priest",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",},

"Rogue",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",},

"Mimic",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",},

"Archer",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",},

"Paladin",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",},

"Ranger",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",},

"Druid",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",},

"Adventurer",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",},

"Shaman",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",},

"Runemaster",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",},

"Mindcrafter",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",},
}
