-- Tables with descriptive text about the races, to be displayed
-- during character creation process. - C. Blue

function get_race_diz(r_title, l)
    local i
    i = 0
    while __races_diz[i * 2 + 1] ~= nil do
	if __races_diz[i * 2 + 1] == r_title then
	    if __races_diz[i * 2 + 2][l + 1] == nil then
		return ""
	    else
		return __races_diz[i * 2 + 2][l + 1]
	    end
	end
	i = i + 1
    end
    return ""
end

__races_diz = {

--  "12345678901234567890123456789012345678901234567890",

"Human",
    {"\255uHumans\255U are allrounders with no special weaknesses ",
    "or strengths. They have no experience penalties   ",
    "and tend to go up in levels faster than most other",
    "races.",
    "They get a bonus on Climbing and Interception.",
    "", "", "", "", "", "", "",},

"Half-Elf",
    {"\255uHalf-elves\255U tend to be smarter and faster than",
    "humans, but not as strong. They are slightly",
    "better at searching, disarming, saving throws,",
    "stealth, bows and magic, but they are not as good",
    "at hand weapons. Half-elves resist light intrinsi-",
    "cally. They get a bonus on Bow-Mastery and on",
    "Interception.",
    "", "", "", "", "",},

"Elf",
    {"\255uElves\255U resist light intrinsically and see invisible",
    "creatures. They are better magicians than humans,",
    "but not as good at fighting. They tend to be wiser",
    "and smarter than humans or half-elves and good at",
    "searching, disarming, perception, stealth, bows/",
    "throwing and magic.",
    "They get a bonus on Bow-Mastery, Magic, Stealth,",
    "Dodging, Calmness and Sneakiness.",
    "", "", "", "",},

"Hobbit",
    {"\255uHobbits\255U have infra-vision, resist black breath",
    "somewhat, have their dexterity sustained and get a",
    "dexterity bonus for not wearing shoes.",
    "They make excellent rogues (they prefer to be",
    "called burglars), but might want to train 'Health'",
    "skill to make up for having lower hit points than",
    "humans. Their strengths are bows/throwing, saving",
    "throw, searching, disarming, perception, stealth.",
    "They receive a bonus on Sling-Mastery, Sneakiness,",
    "Dodging, and especially Stealth.",
    "", "",},

"Gnome",
    {"\255uGnomes\255U live in the earth, in burrow-like",
    "homes. They make excellent spellcasters and resist",
    "paralysis intrinsically. They are good at stealth,",
    "searching, perception and disarming. Weaker than",
    "humans, they aren't very good at close combat.",
    "Gnomes have infra-vision and receive a bonus on",
    "the skills Crossbow-Mastery, Magic, and a large",
    "bonus on Dodging and Digging.",
    "", "", "", "",},

"Dwarf",
    {"\255uDwarves\255U can never be blinded and learn",
    "how to pass even the highest mountain regions at",
    "level 30. They are headstrong miners and fighters",
    "of legend. Strong and wise, they are less intelli-",
    "gent than humans though. Since they live under-"
    "ground they have infra-vision, and their toughness",
    "makes for a good saving throw. They do have one",
    "big drawback, though. Dwarves are loudmouthed and",
    "proud, singing in loud voices, arguing with them-",
    "selves for no good reason, and screaming out chal-",
    "lenges to nearby foes. In other words, dwarves",
    "have miserable stealth.",
    "",},

"Half-Orc",
    {"\255uHalf-Orcs\255U resist darkness because of their",
    "preference to living underground. They make great",
    "warriors and rogues, but are terrible at magic.",
    "Their stealth isn't great either, and they are bad",
    "at disarming, searching and perception. Half-orcs",
    "are quite ugly and tend to pay more for goods in",
    "town. Their constitution however is pretty good.",
    "They receive a slight bonus on Backstabbing and a",
    "large bonus on Weaponmastery, as well as a bonus",
    "on Necromancy. They receive penalties on Magic and",
    "Sorcery.",
    "",},

"Half-Troll",
    {"\255uHalf-trolls\255U have their strength sustained and",
    "are very strong but also stupid and always hungry.",
    "They are so ugly that a half-orc grimaces in their",
    "presence. Half-trolls are bad at searching, disar-",
    "ming, perception and stealth, get a penalty on",
    "Critical-Strike and large penalties on Archery,",
    "Magic and Sorcery, but receive a bonus on Health,",
    "Blunt-Mastery and Swimming.",
    "", "", "", "",},

"Dunadan",
    {"\255uDunadain\255U have their constituation sustained.",
    "They are a hardy race of men from the west. This",
    "elder race surpasses human abilities in every",
    "field, especially constituion. However, being men",
    "of the world, very little is new to them and expe-",
    "rience is harder for them to gain. A Dunadan gets",
    "boni on Combat, Archery and Interception skills,",
    "and a small bonus to Magic.",
    "", "", "", "",},

"High-Elf",
    {"\255uHigh-elves\255U can see the invisible and resist",
    "light and the flow of time intrinsically. They are",
    "a race of immortal beings, dating far back to when",
    "Arda was young, masters of skills, strong and",
    "intelligent, although their wisdom is sometimes",
    "suspect. They do very well in all professions but",
    "there are few things they haven't seen yet and so",
    "experience is hard for them to gain.",
    "High-elves receive boni on Bow-Mastery, Magic,",
    "Stealth, Dodging, and a large bonus on Calmness.",
    "", "",},

"Yeek",
    {"\255uYeeks\255U, being weak and losing many childhood",
    "fights, have intrinsic feather falling.",
    "Often having to escape from precarious situations,",
    "they are able to pass through thick forest easily.",
    "Yeeks are the least powerful of all races and",
    "while they do not have particular strengths or",
    "weaknesses similar as humans, they suffer disad-",
    "vantages in all fields. However, to compensate",
    "they learn very quickly, gaining levels fastest",
    "of all the races.",
    "", "",},

"Goblin",
    {"\255uGoblins\255U have a decidedly mixed reputation.",
    "They are almost always grinning, and more often",
    "than not you cannot tell whether or not they are",
    "eyeing you like a side of meat. They are as sturdy",
    "as dwarves and quite agile, making them good",
    "fighters and rogues. Being creatures of the night",
    "Goblins have natural resistance to darkness.",
    "They receive boni on Boomerang-Mastery and",
    "Stealing.",
    "", "", "",},

--  "12345678901234567890123456789012345678901234567890",
"Ent",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",},

"Draconian",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",},

"Kobold",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",},

"Dark-Elf",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",},

"Vampire",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",},

"Maia",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",},
}
