-- Tables with descriptive text about the races, to be displayed
-- during character creation process. - C. Blue

function get_race_diz(r_title, l)
    local i
    i = 0
    while __races_diz[i * 2 + 1] ~= nil do
	if __races_diz[i * 2 + 1] == r_title then
	    if __races_diz[i * 2 + 2][l + 1] == nil then
		return ""
	    else
		return __races_diz[i * 2 + 2][l + 1]
	    end
	end
	i = i + 1
    end
    return ""
end

__races_diz = {

--  "12345678901234567890123456789012345678901234567890",

"Human",
    {"\255uHumans\255U are allrounders with no special weaknesses ",
    "or strengths. They have no experience penalties   ",
    "and tend to go up in levels faster than most other",
    "races.",
    "They get a bonus on Climbing and Interception.",
    "", "", "", "", "", "", "",},

"Half-Elf",
    {"\255uHalf-elves\255U tend to be smarter and faster than",
    "humans, but not as strong. They are slightly",
    "better at searching, disarming, saving throws,",
    "stealth, bows and magic, but they are not as good",
    "at hand weapons. Half-elves resist light intrinsi-",
    "cally. They get a bonus on Bow-Mastery and on",
    "Interception.",
    "", "", "", "", "",},

"Elf",
    {"\255uElves\255U resist light intrinsically and see invisible",
    "creatures. They are better magicians than humans,",
    "but not as good at fighting. They tend to be wiser",
    "and smarter than humans or half-elves and good at",
    "searching, disarming, perception, stealth, bows/",
    "throwing and magic.",
    "They get a bonus on Bow-Mastery, Magic, Stealth,",
    "Dodging, Calmness and Sneakiness.",
    "", "", "", "",},

"Hobbit",
    {"\255uHobbits\255U have infra-vision, resist black breath",
    "somewhat, have their dexterity sustained and get a",
    "dexterity bonus for not wearing shoes.",
    "They make excellent rogues (they prefer to be",
    "called burglars), but might want to train 'Health'",
    "skill to make up for having lower hit points than",
    "humans.",
    "Strengths: Bows/throwing, saving throw, searching,",
    "disarming, perception, stealth.",
    "Skill boni: Sling-Mastery, Sneakiness, Dodging,",
    "and especially Stealth.",
    "",},

"Gnome",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",},

"Dwarf",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",},

"Half-Orc",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",},

"Half-Troll",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",},

"Dunadan",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",},

"High-Elf",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",},

"Yeek",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",},

"Goblin",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",},

"Ent",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",},

"Draconian",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",},

"Kobold",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",},

"Dark-Elf",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",},

"Vampire",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",},

"Maia",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",},
}
