-- Tables with descriptive text about the traits, to be displayed 
-- during character creation process. - C. Blue

function get_trait_diz(r_title, l)
    local i
    i = 0
    while __traits_diz[i * 2 + 1] ~= nil do
        if __traits_diz[i * 2 + 1] == r_title then
            if __traits_diz[i * 2 + 2][l + 1] == nil then
                return ""
            else
                return __traits_diz[i * 2 + 2][l + 1]
            end
        end
        i = i + 1
    end
    return ""
end

__traits_diz = {

--  "12345678901234567890123456789012345678901234567890",

"N/A",
    {"", "", "", "", "", "", "", "", "", "", "", "",},


"Blue lineage",
    {"The \255ublue\255U lineage provides intrinsic resistance to",
    "lightning, which turns into immunity later.",
    "", "", "", "", "", "", "", "", "", "",},

"White lineage",
    {"The \255uwhite\255U lineage provides intrinsic resistance",
    "to frost, which turns into immunity later.",
    "", "", "", "", "", "", "", "", "", "",},

"Red lineage",
    {"The \255ured\255U lineage provides intrinsic resistance to",
    "fire, which turns into immunity later.",
    "", "", "", "", "", "", "", "", "", "",},

"Black lineage",
    {"The \255ublack\255U lineage provides intrinsic resistance",
    "to acid, which turns into immunity later.",
    "", "", "", "", "", "", "", "", "", "",},

"Green lineage",
    {"The \255ugreen\255U lineage provides intrinsic resistance",
    "to poison, which turns into immunity later.",
    "", "", "", "", "", "", "", "", "", "",},

"Multi-hued lineage",
    {"The \255umulti-hued\255U lineage provides intrinsic",
    "resistance to the four basic elements and poison,",
    "Those four are fire, frost, acid and lightning.",
    "", "", "", "", "", "", "", "", "",},

"Bronze lineage",
    {"The \255ubronze\255U lineage provides intrinsic resistance",
    "to confusion and paralysis and its metallic scales",
    "have a chance to reflect bolts and arrows.",
    "", "", "", "", "", "", "", "", "",},

"Silver lineage",
    {"The \255usilver\255U lineage provides intrinsic resistance",
    "to cold and poison and its metallic scales",
    "have a chance to reflect bolts and arrows.",
    "", "", "", "", "", "", "", "", "",},

"Golden lineage",
    {"The \255ugolden\255U lineage provides intrinsic resistance",
    "to acid and sound and its metallic scales",
    "have a chance to reflect bolts and arrows.",
    "", "", "", "", "", "", "", "", "",},

"Law lineage",
    {"The \255ulaw\255U lineage provides intrinsic resistance to",
    "shards and sound.",
    "", "", "", "", "", "", "", "", "", "",},

"Chaos lineage",
    {"The \255uchaos\255U lineage provides intrinsic resistance",
    "to chaos and disenchantment.",
    "", "", "", "", "", "", "", "", "", "",},

"Balance lineage",
    {"The \255ubalance\255U lineage provides intrinsic resistance",
    "to disenchantment and sound.",
    "", "", "", "", "", "", "", "", "", "",},

"Power lineage",
    {"The \255upower\255U lineage provides intrinsic resistance",
    "to raw magical energy itself.",
    "", "", "", "", "", "", "", "", "", "",},


"Enlightened",
    {"\255uEnlightenment\255U attunes to angelic powers.",
    "", "", "", "", "", "", "", "", "", "", "",},

"Corrupted",
    {"\255uCorruption\255U attunes to demonic powers.",
    "", "", "", "", "", "", "", "", "", "", "",},


"",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "", 
    "",
    "",
    "",},

"",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "", 
    "",
    "",
    "",},

"",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "", 
    "",
    "",
    "",},

"",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "", 
    "",
    "",
    "",},

"",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "", 
    "",
    "",
    "",},

"",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "", 
    "",
    "",
    "",},

"",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "", 
    "",
    "",
    "",},

"",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "", 
    "",
    "",
    "",},

"",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "", 
    "",
    "",
    "",},

"",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "", 
    "",
    "",
    "",},

"",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "", 
    "",
    "",
    "",},

"",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "", 
    "",
    "",
    "",},

"",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "", 
    "",
    "",
    "",},

"",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "", 
    "",
    "",
    "",},

"",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "", 
    "",
    "",
    "",},

"",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "", 
    "",
    "",
    "",},

"",
    {"\255u\255U",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "", 
    "",
    "",
    "",},
}
