FROM registry.fedoraproject.org/fedora:43

COPY .github/docker/fedora43/install-build-requirements.sh /tmp/install-build-requirements.sh
RUN bash /tmp/install-build-requirements.sh \
  && dnf clean all \
  && rm -f /tmp/install-build-requirements.sh

WORKDIR /workspace
